CREATE TABLE store (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Store ID',
    store_code VARCHAR(64) NOT NULL COMMENT 'Store code',
    store_name VARCHAR(128) NOT NULL COMMENT 'Store name',
    contact_phone VARCHAR(32) NULL COMMENT 'Contact phone',
    address VARCHAR(255) NULL COMMENT 'Address',
    status VARCHAR(32) NOT NULL COMMENT 'ENABLED / DISABLED',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_store_code (store_code),
    KEY idx_store_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Store';

CREATE TABLE sys_user (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'User ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    username VARCHAR(64) NULL COMMENT 'Login username',
    password_hash VARCHAR(255) NULL COMMENT 'Password hash',
    real_name VARCHAR(64) NOT NULL COMMENT 'Real name',
    phone VARCHAR(32) NULL COMMENT 'Phone',
    wechat_openid VARCHAR(128) NULL COMMENT 'WeChat openid',
    wechat_unionid VARCHAR(128) NULL COMMENT 'WeChat unionid',
    status VARCHAR(32) NOT NULL COMMENT 'ENABLED / DISABLED',
    last_login_at DATETIME NULL COMMENT 'Last login at',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_phone (phone),
    UNIQUE KEY uk_user_username (username),
    UNIQUE KEY uk_user_wechat_openid (wechat_openid),
    KEY idx_user_store_id (store_id),
    KEY idx_user_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='System user';

CREATE TABLE sys_role (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Role ID',
    store_id BIGINT NULL COMMENT 'Store ID, null for global built-in roles',
    role_code VARCHAR(64) NOT NULL COMMENT 'Role code',
    role_name VARCHAR(64) NOT NULL COMMENT 'Role name',
    status VARCHAR(32) NOT NULL COMMENT 'ENABLED / DISABLED',
    sort_order INT NOT NULL DEFAULT 0 COMMENT 'Sort order',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_role_store_code (store_id, role_code),
    KEY idx_role_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='System role';

CREATE TABLE sys_permission (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Permission ID',
    permission_code VARCHAR(128) NOT NULL COMMENT 'Permission code',
    permission_name VARCHAR(128) NOT NULL COMMENT 'Permission name',
    module_code VARCHAR(64) NOT NULL COMMENT 'Module code',
    status VARCHAR(32) NOT NULL COMMENT 'ENABLED / DISABLED',
    sort_order INT NOT NULL DEFAULT 0 COMMENT 'Sort order',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_permission_code (permission_code),
    KEY idx_permission_status (status),
    KEY idx_permission_module_code (module_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='System permission';

CREATE TABLE sys_user_role (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    user_id BIGINT NOT NULL COMMENT 'User ID',
    role_id BIGINT NOT NULL COMMENT 'Role ID',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_role (user_id, role_id),
    KEY idx_user_role_role_id (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='User role relation';

CREATE TABLE sys_role_permission (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    role_id BIGINT NOT NULL COMMENT 'Role ID',
    permission_id BIGINT NOT NULL COMMENT 'Permission ID',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    PRIMARY KEY (id),
    UNIQUE KEY uk_role_permission (role_id, permission_id),
    KEY idx_role_permission_permission_id (permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Role permission relation';

CREATE TABLE sequence_daily (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Sequence ID',
    seq_type VARCHAR(32) NOT NULL COMMENT 'Sequence type',
    seq_date DATE NOT NULL COMMENT 'Sequence date',
    current_val BIGINT NOT NULL DEFAULT 0 COMMENT 'Current value',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    PRIMARY KEY (id),
    UNIQUE KEY uk_sequence_daily (seq_type, seq_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Daily sequence counter';

CREATE TABLE sys_dict_type (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Dictionary type ID',
    type_code VARCHAR(64) NOT NULL COMMENT 'Type code',
    type_name VARCHAR(128) NOT NULL COMMENT 'Type name',
    status VARCHAR(32) NOT NULL COMMENT 'ENABLED / DISABLED',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dict_type_code (type_code),
    KEY idx_dict_type_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Dictionary type';

CREATE TABLE sys_dict_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Dictionary item ID',
    type_id BIGINT NOT NULL COMMENT 'Dictionary type ID',
    item_code VARCHAR(64) NOT NULL COMMENT 'Item code',
    item_name VARCHAR(128) NOT NULL COMMENT 'Item name',
    sort_order INT NOT NULL DEFAULT 0 COMMENT 'Sort order',
    status VARCHAR(32) NOT NULL COMMENT 'ENABLED / DISABLED',
    is_system TINYINT NOT NULL DEFAULT 0 COMMENT 'System built-in flag',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dict_item_type_code (type_id, item_code),
    KEY idx_dict_item_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Dictionary item';

CREATE TABLE customer (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Customer ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    customer_name VARCHAR(64) NOT NULL COMMENT 'Customer name',
    phone VARCHAR(32) NULL COMMENT 'Phone',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    KEY idx_customer_store_phone (store_id, phone),
    KEY idx_customer_name (customer_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Customer';

CREATE TABLE vehicle (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Vehicle ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    customer_id BIGINT NULL COMMENT 'Customer ID',
    model VARCHAR(128) NULL COMMENT 'Vehicle model',
    frame_no VARCHAR(128) NOT NULL COMMENT 'Frame number',
    battery_no VARCHAR(128) NULL COMMENT 'Battery number',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_vehicle_store_frame_no (store_id, frame_no),
    KEY idx_vehicle_customer_id (customer_id),
    KEY idx_vehicle_battery_no (battery_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Vehicle';

CREATE TABLE part (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Part ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    part_code VARCHAR(64) NOT NULL COMMENT 'System part code',
    official_part_no VARCHAR(128) NULL COMMENT 'Official part number',
    part_name VARCHAR(128) NOT NULL COMMENT 'Part name',
    model VARCHAR(128) NULL COMMENT 'Model',
    source VARCHAR(32) NOT NULL COMMENT 'OFFICIAL / THIRD_PARTY',
    category_code VARCHAR(64) NULL COMMENT 'Category code',
    reference_cost_price DECIMAL(18,4) NULL COMMENT 'Reference cost price',
    default_barcode VARCHAR(128) NULL COMMENT 'Default barcode',
    location_remark VARCHAR(255) NULL COMMENT 'Location remark',
    create_source VARCHAR(32) NOT NULL COMMENT 'NORMAL / INBOUND / WORK_ORDER_TEMP',
    status VARCHAR(32) NOT NULL COMMENT 'ENABLED / DISABLED',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_part_store_code (store_id, part_code),
    KEY idx_part_official_no (official_part_no),
    KEY idx_part_name (part_name),
    KEY idx_part_source (source),
    KEY idx_part_category (category_code),
    KEY idx_part_status (status),
    KEY idx_part_default_barcode (default_barcode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Part master';

CREATE TABLE part_barcode (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Barcode ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    part_id BIGINT NOT NULL COMMENT 'Part ID',
    barcode VARCHAR(128) NOT NULL COMMENT 'Barcode',
    barcode_type VARCHAR(32) NULL COMMENT 'SYSTEM / MANUAL / OFFICIAL',
    is_primary TINYINT NOT NULL DEFAULT 0 COMMENT 'Primary barcode flag',
    status VARCHAR(32) NOT NULL COMMENT 'ENABLED / DISABLED',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_part_barcode_store_barcode (store_id, barcode),
    KEY idx_barcode_part_id (part_id),
    KEY idx_barcode_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Part barcode';

CREATE TABLE inventory_stock (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Inventory stock ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    part_id BIGINT NOT NULL COMMENT 'Part ID',
    actual_qty INT NOT NULL DEFAULT 0 COMMENT 'Actual quantity',
    available_qty INT NOT NULL DEFAULT 0 COMMENT 'Available quantity',
    reserved_qty INT NOT NULL DEFAULT 0 COMMENT 'Reserved quantity',
    last_flow_id BIGINT NULL COMMENT 'Last inventory flow ID',
    last_changed_at DATETIME NULL COMMENT 'Last changed at',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_inventory_stock_store_part (store_id, part_id),
    KEY idx_inventory_stock_part_id (part_id),
    KEY idx_inventory_stock_available_qty (available_qty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Inventory stock snapshot';

CREATE TABLE inventory_flow (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Inventory flow ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    inventory_stock_id BIGINT NOT NULL COMMENT 'Inventory stock ID',
    part_id BIGINT NOT NULL COMMENT 'Part ID',
    flow_type VARCHAR(32) NOT NULL COMMENT 'INBOUND / RESERVE / RELEASE / CONSUME / ADJUST',
    quantity_delta INT NOT NULL COMMENT 'Quantity delta',
    actual_before INT NOT NULL COMMENT 'Actual before',
    actual_after INT NOT NULL COMMENT 'Actual after',
    available_before INT NOT NULL COMMENT 'Available before',
    available_after INT NOT NULL COMMENT 'Available after',
    reserved_before INT NOT NULL COMMENT 'Reserved before',
    reserved_after INT NOT NULL COMMENT 'Reserved after',
    business_type VARCHAR(64) NOT NULL COMMENT 'Business type',
    business_id BIGINT NULL COMMENT 'Business ID',
    work_order_id BIGINT NULL COMMENT 'Work order ID',
    work_order_charge_item_id BIGINT NULL COMMENT 'Work order charge item ID',
    operator_id BIGINT NOT NULL COMMENT 'Operator ID',
    operated_at DATETIME NOT NULL COMMENT 'Operated at',
    reason VARCHAR(255) NULL COMMENT 'Reason',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    PRIMARY KEY (id),
    KEY idx_flow_store_part (store_id, part_id),
    KEY idx_flow_stock_id (inventory_stock_id),
    KEY idx_flow_type (flow_type),
    KEY idx_flow_business (business_type, business_id),
    KEY idx_flow_work_order_id (work_order_id),
    KEY idx_flow_work_order_charge_item_id (work_order_charge_item_id),
    KEY idx_flow_operated_at (operated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Inventory flow';

CREATE TABLE work_order (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Work order ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    work_order_no VARCHAR(64) NOT NULL COMMENT 'Work order number',
    customer_id BIGINT NULL COMMENT 'Customer ID',
    vehicle_id BIGINT NULL COMMENT 'Vehicle ID',
    customer_name_snapshot VARCHAR(64) NOT NULL COMMENT 'Customer name snapshot',
    customer_phone_snapshot VARCHAR(32) NULL COMMENT 'Customer phone snapshot',
    vehicle_model_snapshot VARCHAR(128) NULL COMMENT 'Vehicle model snapshot',
    frame_no_snapshot VARCHAR(128) NULL COMMENT 'Frame number snapshot',
    battery_no_snapshot VARCHAR(128) NULL COMMENT 'Battery number snapshot',
    repair_item VARCHAR(512) NOT NULL COMMENT 'Repair item',
    status VARCHAR(32) NOT NULL COMMENT 'Work order status',
    receivable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT 'Receivable amount snapshot',
    submitted_by BIGINT NULL COMMENT 'Submitted by',
    submitted_at DATETIME NULL COMMENT 'Submitted at',
    settled_by BIGINT NULL COMMENT 'Settled by',
    settled_at DATETIME NULL COMMENT 'Settled at',
    cancelled_by BIGINT NULL COMMENT 'Cancelled by',
    cancelled_at DATETIME NULL COMMENT 'Cancelled at',
    cancel_reason VARCHAR(255) NULL COMMENT 'Cancel reason',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_work_order_no (work_order_no),
    KEY idx_work_order_store_status (store_id, status),
    KEY idx_work_order_store_created (store_id, created_at),
    KEY idx_work_order_customer_id (customer_id),
    KEY idx_work_order_vehicle_id (vehicle_id),
    KEY idx_work_order_frame_no (frame_no_snapshot),
    KEY idx_work_order_created_at (created_at),
    KEY idx_work_order_settled_at (settled_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Work order';

CREATE TABLE work_order_charge_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Work order charge item ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    work_order_id BIGINT NOT NULL COMMENT 'Work order ID',
    charge_type VARCHAR(32) NOT NULL COMMENT 'PART / LABOR / OTHER',
    item_name VARCHAR(255) NOT NULL COMMENT 'Item name',
    part_id BIGINT NULL COMMENT 'Part ID, required for PART',
    part_code_snapshot VARCHAR(64) NULL COMMENT 'Part code snapshot',
    part_name_snapshot VARCHAR(128) NULL COMMENT 'Part name snapshot',
    part_source_snapshot VARCHAR(32) NULL COMMENT 'Part source snapshot',
    quantity INT NOT NULL COMMENT 'Quantity',
    unit VARCHAR(32) NULL COMMENT 'Unit',
    unit_price DECIMAL(18,2) NOT NULL COMMENT 'Unit price',
    line_amount DECIMAL(18,2) NOT NULL COMMENT 'Line amount',
    cost_price_snapshot DECIMAL(18,4) NULL COMMENT 'Cost price snapshot',
    line_cost_amount DECIMAL(18,2) NULL COMMENT 'Line cost amount',
    inventory_affecting TINYINT NOT NULL DEFAULT 0 COMMENT 'Inventory affecting flag',
    is_temp_part TINYINT NOT NULL DEFAULT 0 COMMENT 'Temporary part flag',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE / REMOVED',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    KEY idx_charge_item_order_id (work_order_id),
    KEY idx_charge_item_part_id (part_id),
    KEY idx_charge_item_store_type (store_id, charge_type),
    KEY idx_charge_item_store_part (store_id, part_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Work order charge item';

CREATE TABLE work_order_status_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Work order status log ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    work_order_id BIGINT NOT NULL COMMENT 'Work order ID',
    from_status VARCHAR(32) NULL COMMENT 'From status',
    to_status VARCHAR(32) NOT NULL COMMENT 'To status',
    action_type VARCHAR(64) NOT NULL COMMENT 'CREATE / SUBMIT / CANCEL / SETTLE / UPDATE_STATUS',
    operator_id BIGINT NOT NULL COMMENT 'Operator ID',
    operated_at DATETIME NOT NULL COMMENT 'Operated at',
    reason VARCHAR(255) NULL COMMENT 'Reason',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    PRIMARY KEY (id),
    KEY idx_status_log_order_id (work_order_id),
    KEY idx_status_log_store_operated (store_id, operated_at),
    KEY idx_status_log_action (action_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Work order status log';

CREATE TABLE payment_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Payment record ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    work_order_id BIGINT NOT NULL COMMENT 'Work order ID',
    payment_no VARCHAR(64) NOT NULL COMMENT 'Payment number',
    amount DECIMAL(18,2) NOT NULL COMMENT 'Amount',
    payment_method VARCHAR(32) NOT NULL COMMENT 'Payment method',
    paid_at DATETIME NOT NULL COMMENT 'Paid at',
    receiver_id BIGINT NULL COMMENT 'Receiver ID',
    operator_id BIGINT NOT NULL COMMENT 'Operator ID',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_payment_no (payment_no),
    KEY idx_payment_order_id (work_order_id),
    KEY idx_payment_store_paid_at (store_id, paid_at),
    KEY idx_payment_method (payment_method)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Payment record';

CREATE TABLE refund_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Refund record ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    work_order_id BIGINT NOT NULL COMMENT 'Work order ID',
    refund_no VARCHAR(64) NOT NULL COMMENT 'Refund number',
    amount DECIMAL(18,2) NOT NULL COMMENT 'Amount',
    refund_method VARCHAR(32) NOT NULL COMMENT 'Refund method',
    refunded_at DATETIME NOT NULL COMMENT 'Refunded at',
    operator_id BIGINT NOT NULL COMMENT 'Operator ID',
    reason VARCHAR(255) NOT NULL COMMENT 'Reason',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_refund_no (refund_no),
    KEY idx_refund_order_id (work_order_id),
    KEY idx_refund_store_refunded_at (store_id, refunded_at),
    KEY idx_refund_method (refund_method)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Refund record';

CREATE TABLE official_after_sales (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Official after sales ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    work_order_id BIGINT NOT NULL COMMENT 'Work order ID',
    is_official_after_sales TINYINT NOT NULL DEFAULT 0 COMMENT 'Official after sales flag',
    official_order_no VARCHAR(128) NULL COMMENT 'Official order number',
    official_settlement_amount DECIMAL(18,2) NULL COMMENT 'Official settlement amount',
    official_settlement_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'NOT_REQUIRED / PENDING / SETTLED',
    official_settlement_time DATETIME NULL COMMENT 'Official settlement time',
    official_settlement_operator_id BIGINT NULL COMMENT 'Official settlement operator ID',
    official_settlement_remark VARCHAR(512) NULL COMMENT 'Official settlement remark',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_official_work_order (work_order_id),
    KEY idx_official_store_status (store_id, official_settlement_status),
    KEY idx_official_order_no (official_order_no),
    KEY idx_official_settlement_time (official_settlement_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Official after sales';

CREATE TABLE reimbursement (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Reimbursement ID',
    store_id BIGINT NOT NULL COMMENT 'Store ID',
    reimbursement_no VARCHAR(64) NOT NULL COMMENT 'Reimbursement number',
    applicant_id BIGINT NOT NULL COMMENT 'Applicant ID',
    purpose VARCHAR(255) NOT NULL COMMENT 'Purpose',
    amount DECIMAL(18,2) NOT NULL COMMENT 'Amount',
    confirmed_amount DECIMAL(18,2) NULL COMMENT 'Confirmed amount',
    status VARCHAR(32) NOT NULL COMMENT 'PENDING / CONFIRMED / REJECTED_OR_CANCELLED',
    submitted_at DATETIME NOT NULL COMMENT 'Submitted at',
    confirmed_by BIGINT NULL COMMENT 'Confirmed by',
    confirmed_at DATETIME NULL COMMENT 'Confirmed at',
    rejected_by BIGINT NULL COMMENT 'Rejected by or cancelled by',
    rejected_at DATETIME NULL COMMENT 'Rejected at or cancelled at',
    reject_reason VARCHAR(255) NULL COMMENT 'Reject reason',
    remark VARCHAR(512) NULL COMMENT 'Remark',
    created_by BIGINT NULL COMMENT 'Created by',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_by BIGINT NULL COMMENT 'Updated by',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_reimbursement_no (reimbursement_no),
    KEY idx_reimbursement_store_status (store_id, status),
    KEY idx_reimbursement_applicant (applicant_id),
    KEY idx_reimbursement_submitted_at (submitted_at),
    KEY idx_reimbursement_confirmed_at (confirmed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Reimbursement';
